# Generated by Django 5.1.2 on 2024-11-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_field", models.CharField(db_column="name_", max_length=50)),
                ("price_uah", models.IntegerField(db_column="price_UAH")),
                ("pages", models.IntegerField()),
                ("genre", models.CharField(db_column="genre", max_length=50)),
            ],
            options={
                "db_table": "book",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                ("reader_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_field", models.CharField(db_column="name_", max_length=20)),
                ("surname", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "reader",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("shop_id", models.AutoField(primary_key=True, serialize=False)),
                ("town", models.CharField(max_length=20)),
                ("adress", models.CharField(max_length=30, unique=True)),
                ("hotline", models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                "db_table": "shop",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("pseudonym", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "name_field",
                    models.CharField(
                        blank=True, db_column="name_", max_length=20, null=True
                    ),
                ),
                ("surname", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "book",
                    models.ManyToManyField(related_name="authors", to="polls.book"),
                ),
            ],
            options={
                "db_table": "author",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Purchases",
            fields=[
                ("purchase_id", models.AutoField(primary_key=True, serialize=False)),
                ("purchase_date", models.DateField()),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="polls.book",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="polls.reader",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="polls.shop",
                    ),
                ),
            ],
            options={
                "db_table": "purchases",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback", models.CharField(max_length=200)),
                ("rating", models.IntegerField()),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="polls.purchases",
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
                "managed": True,
            },
        ),
    ]
