# Generated by Django 5.1.2 on 2024-11-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.purchases"
            ),
        ),
        migrations.AlterField(
            model_name="purchases",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.book",
            ),
        ),
        migrations.AlterField(
            model_name="purchases",
            name="reader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.reader"
            ),
        ),
        migrations.AlterField(
            model_name="purchases",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.shop",
            ),
        ),
    ]
