# Generated by Django 5.1.2 on 2024-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_feedback_purchase_alter_purchases_book_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "author_book",
                "managed": False,
            },
        ),
    ]
